"""resource monitor tables

Revision ID: 01721d08d7ba
Revises: 0003_fix_triggers_json
Create Date: 2026-09-30 14:26:33.126150
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0004_resource_monitor'
down_revision: str | None = '0003_fix_triggers_json'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('container_resource_samples',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('container_name', sa.String(length=128), nullable=False),
    sa.Column('compose_service', sa.String(length=96), nullable=True),
    sa.Column('is_quantlab', sa.Boolean(), nullable=False),
    sa.Column('cpu_percent', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('mem_used_mb', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('mem_limit_mb', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cont_res_name_ts', 'container_resource_samples', ['container_name', 'ts'], unique=False)
    op.create_index(op.f('ix_container_resource_samples_ts'), 'container_resource_samples', ['ts'], unique=False)
    op.create_table('host_resource_samples',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cpu_percent', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cpu_count', sa.Integer(), nullable=True),
    sa.Column('mem_used_mb', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('mem_total_mb', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('swap_used_mb', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('swap_total_mb', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('disk_used_gb', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('disk_total_gb', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_host_resource_samples_ts'), 'host_resource_samples', ['ts'], unique=False)
    op.create_table('resource_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_key', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('cpu_peak_percent', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('mem_peak_mb', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key')
    )
    op.create_table('resource_rollups',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('granularity', sa.String(length=8), nullable=False),
    sa.Column('bucket_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scope', sa.String(length=96), nullable=False),
    sa.Column('cpu_avg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('cpu_max', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('mem_avg_mb', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('mem_max_mb', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('granularity', 'bucket_start', 'scope', name='uq_resource_rollup')
    )
    op.create_index('ix_resource_rollups_bucket', 'resource_rollups', ['granularity', 'bucket_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_resource_rollups_bucket', table_name='resource_rollups')
    op.drop_table('resource_rollups')
    op.drop_table('resource_events')
    op.drop_index(op.f('ix_host_resource_samples_ts'), table_name='host_resource_samples')
    op.drop_table('host_resource_samples')
    op.drop_index(op.f('ix_container_resource_samples_ts'), table_name='container_resource_samples')
    op.drop_index('ix_cont_res_name_ts', table_name='container_resource_samples')
    op.drop_table('container_resource_samples')
    # ### end Alembic commands ###
